gui:
  nerdFontsVersion: "3"
  spinner:
    frames: ["ğŸ•› ","ğŸ• ","ğŸ•‘ ","ğŸ•’ ","ğŸ•“ ","ğŸ•” ","ğŸ•• ","ğŸ•– ","ğŸ•— ","ğŸ•˜ ","ğŸ•™ ","ğŸ•š "]
    rate: 100
git:
  ignoreWhitespaceInDiffView: true
  log:
    showGraph: 'when-maximised'
    showWholeGraph: true
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
